
AddCSLuaFile()

GF2Models = { 
	["centaureissi"] = true,
	["charolic"] = true,
	["cheeta"] = true,
	["colphne"] = true,
	["daiyan"] = true,
	["groza"] = true,
	["jiangyu"] = true,
	["lenna"] = true,
	-- ["nagant"] = true,
	["nemesis"] = true,
	["peritya"] = true,
	["qiongjiu"] = true,
	["sharkry"] = true,
	["tololo"] = true,
	["vepley"] = true,
	["sabrina"] = true,
	["macqiato"] = true,
	
	["groza_violet_rain"] = true,
	["daiyan_exquisite_jade"] = true,
	["charolic_leaping_rabbit"] = true,
	["lenna_energetic_magic"] = true,
	["vepley_sparkling_wish"] = true,
	["macqiato_ballroom"] = true,
	
	["centaureissi_combat"] = true,
	["charolic_combat"] = true,
	["cheeta_combat"] = true,
	["colphne_combat"] = true,
	["daiyan_combat"] = true,
	["groza_combat"] = true,
	["jiangyu_combat"] = true,
	["ksenia_combat"] = true,
	["lenna_combat"] = true,
	["littara_combat"] = true,
	["mosin_nagant_combat"] = true,
	["nagant_combat"] = true,
	["nemesis_combat"] = true,
	["peritya_combat"] = true,
	["qiongjiu_combat"] = true,
	["tololo_combat"] = true,
	["sharkry_combat"] = true,
	["vepley_combat"] = true,
	["sabrina_combat"] = true
}
